import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import localFont from 'next/font/local'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Course.ai",
  description: "Generated by create next app",
};

const productsans = localFont({
  src: [
    {
      path: '../assets/fonts/product-sans/Product-Sans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/product-sans/Product-Sans-Bold.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/product-sans/Product-Sans-Bold.ttf',
      weight: '300',
      style: 'semibold',
    },
    {
      path: '../assets/fonts/product-sans/Product-Sans-Bold-Italic.ttf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../assets/fonts/product-sans/Product-Sans-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    
    
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={productsans.className}>
       
        {children}
        </body>
    </html>
  );
}
